# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            0-PHAT
tagline:          'Yet another hacking blog'
description:      '<span style="color:white">Alessandro Grisa</span><br/>Cyber Security Enthusiast'
url:              zer0phat.github.io
baseurl:          /
images:           /public/images

previews:         /_previews/

author:
  name:           'Alessandro Grisa'
  url:            https://twitter.com/zer0phat

paginate:         5

# Custom vars

github:
  repo:           https://github.com/zer0phat/
